<?php

/**
 * Implements hook_menu().
 */

function geofield_test_menu() {
  $items = array();

  $items['geofield-formapi-element'] = array(
    'title' => 'Geofield native element test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geofield_test_formapi_element_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['geofield-formapi-element/submit'] = array(
    'title' => 'Geofield native element test - Submit page',
    'page callback' => 'geofield_test_latlon_submit_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['geofield-proximity-element'] = array(
    'title' => 'Geofield proximity element test',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('geofield_test_formapi_proximity_form'),
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Form API callback for geofield native formapi field.
 */

function geofield_test_formapi_element_form() {
  $form = array();

  $form['geofield_latlon_simple'] = array(
    '#type' => 'geofield_latlon',
  );

  $form['geofield_latlon_verbose'] = array(
    '#type' => 'geofield_latlon',
    '#title' => t('Verbose Lat/Lon'),
    '#description' => t('This form element defines a variety of different elements.'),
    '#default_value' => array(
      'lat' => '41',
      'lon' => '-86',
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}

function geofield_test_formapi_element_form_submit($form, &$form_state) {
  variable_set('geofield_test_simple_latlon', $form_state['values']['geofield_latlon_simple']);
  drupal_goto('geofield-formapi-element/submit');
}

function geofield_test_latlon_submit_page() {
  $content = array();
  $simple = variable_get('geofield_test_simple_latlon', FALSE);
  if ($simple) {
    $content['simple'] = array('#markup' => '<h2>Simple</h2><p>Lat: ' . $simple['lat'] . ' Lon: ' . $simple['lon'] . '</p>');
  }
  return $content;
}

/**
 * Form API callback for proximity formapi element.
 */

function geofield_test_formapi_proximity_form() {
  $form = array();

  $form['geofield_proximity'] = array(
    '#type' => 'geofield_proximity',
    '#title' => t('Proximity field - Simple'),
    '#description' => t('Test description'),
    '#default_value' => array(
      'origin' => '',
      'distance' => 0,
      'unit' => GEOFIELD_KILOMETERS,
    ),
  );

  $form['geofield_proximity_range'] = array(
    '#type' => 'geofield_proximity',
    '#title' => t('Proximity field - Range'),
    '#description' => t('Test description'),
    '#default_value' => array(
      'origin' => '',
      'distance' => 0,
      'unit' => GEOFIELD_KILOMETERS,
    ),
    '#geofield_range' => TRUE,
  );


  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

  return $form;
}