<?php
/**
 * @file
 * This is an another airtribune module, which have big weight, so this module called last.
 * Module used for overridde some variables, defined in contrib and another modules.
 */

/**
 * Implements of hook_js_alter.
 * Unset CSV script, to escape overriding already defined values.
 * @see #4025
 */
function at_high_weight_js_alter(&$js){
  if (strpos($_GET['q'], 'editablefields') !== FALSE || $_POST['form_id'] == 'editablefields_as_link_form') {
    if (variable_get('clientside_validation_use_minified', 0) == 0) {
      unset($js[drupal_get_path('module', 'clientside_validation') . '/jquery-validate/jquery.validate.js']);
    } else {
      unset($js[drupal_get_path('module', 'clientside_validation') . '/jquery-validate/jquery.validate.min.js']);
    }
  }
}

/**
 * Implements of hook_css_alter.
 * Unset CSS, loaded by editablefields_as_link from default theme. Don't need this CSS in /admin/* section.
 * @see #4025
 */
function at_high_weight_css_alter(&$css){
  if (strpos($_GET['q'], 'editablefields') !== FALSE || $_POST['form_id'] == 'editablefields_as_link_form') {
    foreach ($css as $key => $value) {
      // 'airtribune2' || 'sites/all/themes/adaptivetheme/at_core'
      if (strpos($key, $GLOBALS['theme']) || strpos($key, $GLOBALS['path_to_at_core'])) {
        unset($css[$key]);
      }
    }
  }
}