<?php

define('AIRTRIBUNE_LANGUAGES_ICONSET', 'shiny');

/**
 * Implements hook_ctools_plugin_directory().
 */
function airtribune_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme().
 */
function airtribune_theme() {
  return array(
    'airtribune_user_pane' => array(
      'template' => 'airtribune-user-pane',
      'path' => drupal_get_path('module', 'airtribune') . '/plugins/content_types/airtribune_user',
      'file' => 'airtribune_user.inc',
      'render element' => 'elements',
    ),
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function airtribune_field_formatter_info() {
  return array(
    'adapitve_dates' => array(
      'label' => t('Adaptive'),
      'field types' => array('datetime'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function airtribune_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  foreach ($items as $delta => $item) {
    $date1 = getdate($ts1 = strtotime($item['value']));
    $date2 = getdate($ts2 = strtotime($item['value2']));

    // 23 Dec, 2012 — 5 Jan, 2013
    if ($date1['year'] != $date2['year']) {
      $dates = date('d M, Y', $ts1) . ' — ' . date('d M, Y', $ts2);
    }
    // 28 Aug — 3 Sep, 2012
    elseif ($date1['mon'] != $date2['mon']) {
      $dates = date('d M', $ts1) . ' — ' . date('d M, Y', $ts2);
    }
    // 24 — 26 Aug, 2012
    else {
      $dates = date('d', $ts1) . ' — ' . date('d M, Y', $ts2);
    }
    $element[$delta] = array('#markup' => $dates);
  }
  return $element;
}



/**
 * See issue #2370.
 */
function airtrubune_format_username($account) {
  return $account->name;
}
