<?php

include_once 'at_tracker.field.inc';
include_once 'at_tracker.storage.inc';

/**
* Implements hook_views_api().
*/
function at_tracker_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'at_tracker') . '/views',
  );
}

/**
* Implements hook_field_create_field().
*/
function at_tracker_field_create_field($field) {
  if ($field['type'] == 'at_tracker') {
    $field['storage'] = array(
        'type' => 'at_tracker_field_storage',
        'settings' => array(),
        'module' => 'at_tracker',
        'active' => 1,
    );

    // Build record to update.
    $record = array(
      'id' => $field['id'],
      'storage_type' => $field['storage']['type'],
      'storage_module' => $field['storage']['module'],
      'storage_active' => $field['storage']['active'],
    );

    // Update the field storage.
    $primary_key = array('id');
    drupal_write_record('field_config', $record, $primary_key);
  }
}

/**
* Implements hook_field_update_field().
*/
function at_tracker_field_update_field($field) {
  at_tracker_field_create_field($field);
}

/**
 *  Create a new form
 */
function at_tracker_editable_widget_form($form, &$form_state, $entity_type, $entity, $field, $instance, $langcode, $delta = 0, $row_index = 0) {
  $items = $entity->{$field['field_name']};
  $items = isset($items[$langcode]) ? $items[$langcode] : array();
  $form['#row_index'] = $row_index;

  // Wrap the whole form into a wrapper, and prepare AJAX settings.
  $wrapper_id = drupal_html_id('at-tracker-editable-' . $field['field_name'] . '-' . $row_index);
  $form['#prefix'] = '<div id="' . $wrapper_id . '" class="editable-' . $field['type'] . ' editable-item">';
  $form['#suffix'] = '</div>';
  $form['#entity_type'] = $entity_type;
  $form['#entity'] = $entity;
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  $form['#entity_id'] = $id;
  $widget_form = field_default_form($entity_type, $entity, $field, $instance, $langcode, $items, $form, $form_state, $delta);
  unset($widget_form[$field['field_name']][LANGUAGE_NONE][0]['value']['#title']);
  // Add field widget into form
  $form += $widget_form;

  return $form;
}
