<?php

/**
 * See #2686, #4317
 *
 * Accommodation aliases are updated in case:
 * - Accommodation added
 * - Accommodation deleted
 * - Accommodation name changed
 * - Event alias changed
 *
 * Same for Activity
 */


// TODO: Move constants to airtribune.module
// Rewrite using Rules.

/**
 * NOTES:
 * If event's coordinates are signifintly changes, there could remain
 * trash aliases for related accommodations (they won't be deleted).
 */

// ***************************************
// Hooks (entity)
// ***************************************

/**
 * Implements hook_entity_insert.
 */
function at_alias_entity_insert($entity, $entity_type) {
  at_alias_entity_hook_implementation('insert', $entity, $entity_type);
}

/**
 * Implements hook_entity_update.
 */
function at_alias_entity_update($entity, $entity_type) {
  at_alias_entity_hook_implementation('update', $entity, $entity_type);
}

/**
 * Implements hook_entity_delete.
 */
function at_alias_entity_delete($entity, $entity_type) {
  at_alias_entity_hook_implementation('delete', $entity, $entity_type);
}



// ***************************************
// Hooks (node)
// ***************************************

/**
 * Implements hook_node_presave.
 * @todo: substitute node path for all types of nodes and entities.
 */
function at_alias_node_presave($node) {
  module_load_include('inc', 'at_alias', 'at_alias.event');
  // Remove event old alias.
  if (!$node->is_new && $node->nid){
    switch ($node->type) {
      case AIRTRIBUNE_PG_CONTEST_TYPE :
      case AIRTRIBUNE_HG_CONTEST_TYPE :
        $query = db_delete('url_alias');
        $query->condition('source', 'event/' . $node->nid);
        $query->execute();
        break;
    }
  }
  _at_alias_substitute_event_node_path($node);
}

/**
 * Implements hook_node_insert.
 */
function at_alias_node_insert($node) {
  at_alias_node_hook_implementation('insert', $node);
}

/**
 * Implements hook_node_update.
 */
function at_alias_node_update($node) {
  at_alias_node_hook_implementation('update', $node);
}

/**
 * Implements hook_node_delete.
 */
function at_alias_node_delete($node) {
  at_alias_node_hook_implementation('delete', $node);
}




// ***************************************
// Helper functions
// ***************************************

function at_alias_node_hook_implementation($op, $node) {
  //~ return;
  module_load_include('inc', 'at_alias', 'at_alias.node');
  module_load_include('inc', 'at_alias', 'at_alias.entity');
  switch ($node->type) {
    case AIRTRIBUNE_ACCOMMODATION_TYPE :
    case AIRTRIBUNE_ACTIVITY_TYPE :
    case AIRTRIBUNE_DAY_TYPE:
      _at_alias_process_single_conjugate_node($op, $node);
      break;
    case AIRTRIBUNE_PG_CONTEST_TYPE :
    case AIRTRIBUNE_HG_CONTEST_TYPE :
      $event = $node;
      _at_alias_process_event_conjugate_nodes($op, $event, AIRTRIBUNE_ACCOMMODATION_TYPE);
      _at_alias_process_event_conjugate_nodes($op, $event, AIRTRIBUNE_ACTIVITY_TYPE);
      _at_alias_process_event_conjugate_nodes($op, $event, AIRTRIBUNE_DAY_TYPE);

      _at_alias_process_event_conjugate_entities($op, $event, AIRTRIBUNE_RACE_ENTITY_TYPE);
      break;
  }
}

/**
 * This function is called from with node module hooks (e.g. hook_insert()).
 *
 * @todo: maybe move into presave hook
 */
function at_alias_module_node_hook_implementation($op, $node) {
  module_load_include('inc', 'at_alias', 'at_alias.event');
  if (in_array($node->type, array(AIRTRIBUNE_PG_CONTEST_TYPE, AIRTRIBUNE_HG_CONTEST_TYPE))) {
    _at_alias_process_event_pages($op, $node);
  }
}

// @todo:
function at_alias_entity_hook_implementation($op, $entity, $entity_type) {
  module_load_include('inc', 'at_alias', 'at_alias.entity');
  switch ($entity_type) {
    case AIRTRIBUNE_RACE_ENTITY_TYPE:
      _at_alias_process_single_conjugate_ent_race($op, $entity);
      break;
    case AIRTRIBUNE_TEAM_TYPE:
      _at_alias_process_single_conjugate_ent_race($op, $entity);
      break;
    case 'user':
      _at_alias_process_user($op, $entity);
      break;
  }
}

/**
 * Helper function.
 * Prepare path for alias using pathauto functionality.
 */
function _at_alias_clear_string($string) {
  module_load_include('inc', 'pathauto');
  if (function_exists('pathauto_cleanstring') && !empty($string)) {
    $path = pathauto_cleanstring($string);
  }

  return !empty($path) ? $path : FALSE;
}

// ***************************************
// Hooks (misc)
// ***************************************


/**
 * Implements hook_form_node_form_alter().
 *
 * Substitute node path.
 * @see at_alias_node_presave()
 * @todo: comment
 */
function at_alias_form_node_form_alter(&$form, $form_state, $form_id) {
  module_load_include('inc', 'at_alias', 'at_alias.event');

  // Set default path alias values for node form.
  // TODO: Make sure that this is always fired after path_form_node_form_alter().
  // @todo: Add content type check
  if (!empty($form['#node']->nid)) {
    $conditions = array('source' => 'event/' . $form['#node']->nid);
    $path = _at_alias_event_path_load($conditions);
    if (!empty($path)) {
      $form['path']['#collapsed'] = empty($path['alias']);
      $form['path']['alias']['#default_value'] = $path['alias'];
      $form['path']['pid']['#value'] = $path['pid'];
      $form['path']['source']['#value'] = $path['source'];
      $form['path']['language']['#value'] = $path['language'];
    }
  }
}

// @todo: Change module weight instead, not to call this hook every time.

/**
 * Implements hook_module_implements_alter().
 *
 * We need $form['path'] to be already added by path.module
 */
function at_alias_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && isset($implementations['at_alias'])) {
    $group = $implementations['at_alias'];
    unset($implementations['at_alias']);
    $implementations['at_alias'] = $group;
  }
}

function at_alias_get_count_of_aliases($path) {
  return db_query("SELECT COUNT(*) FROM {url_alias} WHERE source = :source", array(':source' => $path))->fetchField();
}
