<?php
/**
 * @file
 * Code for the Advert feature.
 */

include_once 'advert.features.inc';

/**
 * Implements hook_node_info().
 */
function advert_node_info() {
  $items = array(
    'advert' => array(
      'name' => t('Advertisement'),
      'base' => 'advert',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implementation of hook_form
 * Default base is 'node_content'
 * @param type $node
 * @param type $form_state
 */
function advert_form($node, $form_state) {
  //Default base is 'node_content'
  //Title field is not attached otherwise
  $form = node_content_form($node, $form_state);
  return $form;
}
