<?php

define('VIEWS_EVENTS_LIST', 'events_list');

define('VIEWS_EVENTS_LIST_NEXT', 'page_events_next');
define('VIEWS_EVENTS_LIST_CURRENT', 'page_events_current');
define('VIEWS_EVENTS_LIST_PAST', 'page_events_past');

define('AT_VIEWS_TABS_CACHE_CID', 'at_views_tabs');

define('AT_CONTEST_CONTENT_TYPE', 'pg_contest');

define('MAIN_PROFILE_TYPE', 'main');
define('CONTESTANT_MEMBERSHIP_TYPE', 'pg_contestant');

/**
 * Implements hook_menu_alter().
 */
function at_helper_menu_alter(&$items) {
  $items['user/login']['title'] = 'Sign in';
  $items['user/register']['title'] = 'Register new user';

  $items['user/register']['weight'] = 0;
  $items['user/login']['weight'] = 1;
  $items['user/password']['weight'] = 2;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function at_helper_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($router_item['tab_root'] == 'events') {
    $tabs = array(
      'events/next' => VIEWS_EVENTS_LIST_NEXT,
      'events/current' => VIEWS_EVENTS_LIST_CURRENT,
      'events/past' => VIEWS_EVENTS_LIST_PAST,
    );
    if (!empty($data['tabs'][0]['output'])) {
      foreach ($data['tabs'][0]['output'] as $key => $tab) {
        $path = $tab['#link']['path'];
        if (in_array($path, array_keys($tabs)) && !at_helper_contest_link_show($tabs[$path])) {
          unset($data['tabs'][0]['output'][$key]);
          $data['tabs'][0]['count']--;
        }
      }
    }
  }
}

// TODO: take user timezone into consideration
/**
 * Check weather to show/hide current tab;
 */
function at_helper_contest_link_show($display_id, $break = FALSE) {
  $match = FALSE;

  $current_time = time();
  $data = at_helper_contest_cache_get();
  switch ($display_id) {
    case VIEWS_EVENTS_LIST_NEXT:
      if (!empty($data['next_start_max'])) {
        if (strtotime($data['next_start_max']) > $current_time) {
          $match = TRUE;
        }
      }
      break;
    case VIEWS_EVENTS_LIST_CURRENT:
      // Check for lasting at the moment events.
      if (!empty($data['current_finish_max'])) {
        if (strtotime($data['current_finish_max']) >= $current_time) {
          $match = TRUE;
        }
      }
      // Check for closest next events.
      elseif (!empty($data['current_start_min']) && strtotime($data['current_start_min']) <= $current_time) {
        if (!$break) {
          // If closest event could have already started or even finished, update cache.
          at_helper_contest_cache_update();
          $match = at_helper_contest_link_show($display_id, TRUE);
        }
        // Avoid infinite cycles.
        else {
          $match = FALSE;
        }
      }
      break;
    case VIEWS_EVENTS_LIST_PAST:
      if (!empty($data['last_finish_min'])) {
        if (strtotime($data['last_finish_min']) < $current_time) {
          $match = TRUE;
        }
      }
      break;
  }
  return $match;
}


/**
 * Get cached contest periods info.
 */
function at_helper_contest_cache_get() {
  $cache = cache_get(AT_VIEWS_TABS_CACHE_CID);
  if (!$cache) {
    $data = at_helper_contest_cache_update();
  }
  else {
    $data = $cache->data;
  }
  return $data;
}

/**
 * Update cache.
 */
function at_helper_contest_cache_update() {
  $data = array(
    'next_start_max' => NULL,
    'current_finish_max' => NULL, // Greatest among current
    'current_start_min' => NULL, // Lowest among next. If it is <= current, cache should be updated
    'last_finish_min' => NULL,
  );

  // Next
  $result_next = views_get_view_result(VIEWS_EVENTS_LIST, VIEWS_EVENTS_LIST_NEXT);
  $start_max = $start_max_timestamp = NULL;
  $start_min = $start_min_timestamp = NULL;
  if (!empty($result_next)) {
    foreach ($result_next as $row) {
      if (!isset($row->field_field_dates[0]['raw']['value'])) {
        continue;
      }
      $start = $row->field_field_dates[0]['raw']['value'];
      // Look for maximum start among next events.
      if (empty($start_max) || (!empty($start_max) && strtotime($start) > $start_max_timestamp)) {
        $start_max = $start;
        $start_max_timestamp = strtotime($start_max);
      }

      // Look for minimum start among next events. Used for current events tab.
      if (empty($start_min) || (!empty($start_min) && strtotime($start) < $start_min_timestamp)) {
        $start_min = $start;
        $start_min_timestamp = strtotime($start_min);
      }
    }
  }
  $data['next_start_max'] = $start_max;
  $data['current_start_min'] = $start_min;

  // Current
  $finish_max = $finish_max_timestamp = NULL;
  $result_current = views_get_view_result(VIEWS_EVENTS_LIST, VIEWS_EVENTS_LIST_CURRENT);
  if (!empty($result_current)) {
    foreach ($result_current as $row) {
      if (!isset($row->field_field_dates[0]['raw']['value']) || !isset($row->field_field_dates[0]['raw']['value2'])) {
        continue;
      }
      $start = $row->field_field_dates[0]['raw']['value'];
      $finish = $row->field_field_dates[0]['raw']['value2'];
      // Look for maximum finish amoung current events.
      if (empty($finish_max) || (!empty($finish_max) && strtotime($finish) >= $finish_max_timestamp)) {
        $finish_max = $finish;
        $finish_max_timestamp = strtotime($finish);
      }
    }
  }
  $data['current_finish_max'] = $finish_max;


  // Past
  $finish_min = $finish_min_timestamp = NULL;
  $result_past = views_get_view_result(VIEWS_EVENTS_LIST, VIEWS_EVENTS_LIST_PAST);
  if (!empty($result_past)) {
    foreach ($result_past as $row) {
      if (!isset($row->field_field_dates[0]['raw']['value2'])) {
        continue;
      }
      $finish = $row->field_field_dates[0]['raw']['value2'];
      // Look form minimum finish among last.
      if (empty($finish_min) || (!empty($finish_min) && strtotime($finish) > $finish_min_timestamp)) {
        $finish_min = $finish;
        $finish_min_timestamp = strtotime($finish_min);
      }
    }
  }
  $data['last_finish_min'] = $finish_min;

  cache_clear_all(AT_VIEWS_TABS_CACHE_CID, 'cache');
  cache_set(AT_VIEWS_TABS_CACHE_CID, $data);
  return $data;
}

/**
 * Implements hook_node_insert().
 */
function at_helper_node_insert($node) {
  cache_clear_all(AT_VIEWS_TABS_CACHE_CID, 'cache');
}

/**
 * Implements hook_node_update().
 */
function at_helper_node_update($node) {
  cache_clear_all(AT_VIEWS_TABS_CACHE_CID, 'cache');
}

/**
 * Implements hook_node_delete().
 */
function at_helper_node_delete($node) {
  cache_clear_all(AT_VIEWS_TABS_CACHE_CID, 'cache');
}


// =================================================
// User Registration
// =================================================

/**
 * Implements hook_node_delete().
 */
function at_helper_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form' :
      $form['#validate'][] = 'at_helper_user_reg_form_validate';
      $form['actions']['submit']['#value'] = t('Register');
      $form['account']['pass']['#after_build'][] = '_at_helper_user_register_form_after_build';
      // TODO: Add after_build only when performing ajax validation.
      $form['#after_build'][] = '_at_helper_user_register_extra_after_build';

      // TODO: Add after_build only when performing ajax validation.
      $form['#after_build'][] = '_at_helper_og_form_extra_after_build';

      break;
    case 'user_profile_form' :
      $form['account']['pass']['#after_build'][] = '_at_helper_user_register_form_after_build';
      // TODO: Add after_build only when performing ajax validation.
      $form['#after_build'][] = '_at_helper_user_register_extra_after_build';
      break;
    case 'user_pass' :
      $form['actions']['submit']['#value'] = t('Request new password');
      break;
    case 'user_login' :
      $form['actions']['submit']['#value'] = t('Sign in');
      break;
    case 'og_ui_confirm_subscribe' :
      $form['#validate'][] = 'at_helper_og_form_validate';
      // TODO: Add after_build only when performing ajax validation.
      $form['#after_build'][] = '_at_helper_user_register_extra_after_build';
      // TODO: Add after_build only when performing ajax validation.
      $form['#after_build'][] = '_at_helper_og_form_extra_after_build';
      break;
  }
}

function _at_helper_user_register_extra_after_build($form, $form_state) {

  if (isset($form['profile_main']['field_birthdate']) && isset($form['profile_main']['field_full_name'])) {
    $form['profile_main']['field_birthdate']['und'][0]['#element_validate'][] = 'at_helper_user_reg_form_validate';
    // TODO: This returns error for multiform ajax.
    $form['profile_main']['field_full_name']['und'][0]['#element_validate'][] = 'at_helper_user_reg_form_validate';
  }

  return $form;
}

function _at_helper_og_form_extra_after_build($form, $form_state) {

  if (isset($form['field_contestant_number'])) {
    $form['field_contestant_number']['und'][0]['#element_validate'][] = 'at_helper_og_form_validate';
  }
  return $form;
}

/**
 * Password element #after_build.
 */
function _at_helper_user_register_form_after_build($element, $form_state) {
  $element['#attached']['js'][1]['data']['password']['confirmSuccess'] = t('Passwords match.');
  $element['#attached']['js'][1]['data']['password']['confirmFailure'] = t('Passwords do not match.');
  $element['#attached']['js'][1]['data']['password']['easyToGuess'] = t('This password is too simple and easy to guess.');

  $element['#attached']['js'][1]['data']['password']['weak'] = t('Weak password.');
  $element['#attached']['js'][1]['data']['password']['fair'] = t('Fair password.');
  $element['#attached']['js'][1]['data']['password']['good'] = t('Good password.');
  $element['#attached']['js'][1]['data']['password']['strong'] = t('Strong password.');
  $element['#attached']['js'][1]['data']['password']['required'] = t('Password is required.');
  $element['pass1']['#description'] = t('Minimum 6 characters.');
  $element['pass2']['#description'] = t('Type a new password in both fields.');
  unset($element['#description']);
  return $element;
}

/**
 * Alter Name field widget
 */
function at_helper_field_widget_form_alter(&$element, &$form_state, $context) {
  if (!empty($element['#field_name']) && !empty($element['#required'])) {
    switch ($element['#field_name']) {
      case 'field_full_name' :
        $element['#after_build'] = array('_at_helper_addressfield_after_build');
        break;
      case 'field_birthdate' :
        $element['#title'] .= " " . theme('form_required_marker');
        $element['#after_build'] = array('_at_helper_datefield_after_build');

        break;
    }
  }

  if (!empty($element['#field_name'])) {
    switch ($element['#field_name']) {
      case AIRTRIBUNE_RACE_START_END_FIELD :
      case AIRTRIBUNE_PG_RACE_WINDOW_OPEN_CLOSE_FIELD :
        $element['#after_build'] = array('_at_helper_race_time_after_build');
        break;
    }
  }
}

/**
 * Change date components labels.
 */
function _at_helper_race_time_after_build($element, $form_state) {
  $labels = array(
    AIRTRIBUNE_RACE_START_END_FIELD => array(
      'value' => t('Start time'),
      'value2' => t('Task deadline time'),
    ),
    AIRTRIBUNE_PG_RACE_WINDOW_OPEN_CLOSE_FIELD => array(
      'value' => t('Window open time'),
      'value2' => t('Window close time'),
    ),
  );
  $element['value']['#title'] = $labels[$element['#field_name']]['value'];
  $element['value2']['#title'] = $labels[$element['#field_name']]['value2'];
  return $element;
}

/**
 * Add #pre_render to name field components.
 */
function _at_helper_addressfield_after_build($element, $form_state) {
  foreach ($element['#components'] as $k => $component) {
    if (empty($component['#exclude'])) {
      $element[$k]['#pre_render'][] = '_at_helper_addressfield_pre_render';
    }
  }
  return $element;
}

function _at_helper_datefield_after_build($element, $form_state) {
  $element['value']['year']['#options'][''] = t('Year');
  $element['value']['month']['#options'][''] = t('Month');
  $element['value']['day']['#options'][''] = t('Day');
  $element['value']['month']['#options'] = array_replace(
    $element['value']['month']['#options'],
    array(
      1 => t('January'),
      2 => t('February'),
      3 => t('March'),
      4 => t('April'),
      5 => t('May'),
      6 => t('June'),
      7 => t('July'),
      8 => t('August'),
      9 => t('September'),
      10 => t('October'),
      11 => t('November'),
      12 => t('December'),
    )
  );
  return $element;
}


/**
 * Add #required asterisk to name field components.
 */
function _at_helper_addressfield_pre_render($element) {
  $element['#required'] = TRUE;
  return $element;
}

function at_helper_user_reg_form_validate($form, &$form_state) {
  global $user;

  // Do nothing for authorized user.
  if ($user->uid) {
    return;
  }

  $profile_type = 'profile_' . MAIN_PROFILE_TYPE;
  if (empty($form_state['values'][$profile_type])) {
    return;
  }
  $profile_values = $form_state['values'][$profile_type];
  $error = FALSE;
  $given = !empty($profile_values['field_full_name']['und'][0]['given']) ? $profile_values['field_full_name']['und'][0]['given'] : FALSE;
  $family = !empty($profile_values['field_full_name']['und'][0]['family']) ? $profile_values['field_full_name']['und'][0]['family'] : FALSE;
  $birthdate = !empty($profile_values['field_birthdate']['und'][0]['value']) ? $profile_values['field_birthdate']['und'][0]['value'] : FALSE;

  //watchdog('tmp', $birthdate . ' ' . $time->validGranularity('year', 'month', 'day'));
  if (!empty($given) && !empty($family) && !empty($birthdate)) {
    $time = new DateObject($birthdate);
    $birthdate = $time->format('Y-m-d H:i:s');
    if (!$time->validGranularity('year', 'month', 'day')) {
      return;
    }
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'profile2');
    $query->entityCondition('bundle', MAIN_PROFILE_TYPE);
    $query->fieldCondition('field_full_name', 'given', $given);
    $query->fieldCondition('field_full_name', 'family', $family);
    $query->fieldCondition('field_birthdate', 'value', $birthdate);
    $orig_query = clone $query;
    $name_exists = $query->count()->execute();
    /*
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'profile2');
    $query->entityCondition('bundle', MAIN_PROFILE_TYPE);
    $query->fieldCondition('field_birthdate', 'value', $birthdate);
    $birthdate_exists = $query->count()->execute();
    */
    // Set form error if Name and Birthdate already exist.
    //if ($name_exists && $birthdate_exists) {

    if ($name_exists) {
      $element = isset($form[$profile_type]) ? $form[$profile_type]['field_full_name'] : $form;
      form_error($element, t('This name, surname and date of birth combination already exist. <a href="!path">Forgot your password?</a>', array('!path' => url('user/password'))));
    }
  }
}

function at_helper_og_form_validate($form, &$form_state) {
  $values = $form_state['values'];
  $gid = !empty($values['gid']) ? $values['gid'] : FALSE;
  $pilot_number = !empty($values['field_contestant_number']['und'][0]['value'])
    ? $values['field_contestant_number']['und'][0]['value']
    : FALSE;
  //watchdog('test', $gid . ' ' . $pilot_number);
  if ($gid && $pilot_number) {
    // TODO:
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'og_membership');
    $query->entityCondition('bundle', CONTESTANT_MEMBERSHIP_TYPE);
    $query->propertyCondition('gid', $gid);
    $query->fieldCondition('field_contestant_number', 'value', $pilot_number);
    //$query->fieldCondition('field_full_name', 'family', $family);
    $number_exists = $query->count()->execute();
    if ($number_exists) {
      $element = isset($form['field_contestant_number']) ? $form['field_contestant_number'] : $form;
      form_error($element, t('This number is used by another pilot.'));
    }
  }
}

/**
 * Implements hook_views_query_alter()
 */
function at_helper_views_query_alter(&$view, &$query) {
  if ($view->name == 'events_map') {
    // Remove extra filters.
    switch ($_GET['q']) {
      case 'events/past' :
        unset($query->where[1]['conditions'][2]);
        unset($query->where[1]['conditions'][4]);
        unset($query->where[1]['conditions'][5]);
        break;
      case 'events/next' :
        unset($query->where[1]['conditions'][3]);
        unset($query->where[1]['conditions'][4]);
        unset($query->where[1]['conditions'][5]);
        break;
      default :
        unset($query->where[1]['conditions'][2]);
        unset($query->where[1]['conditions'][3]);
        break;
    }
  }
}

/**
 * Implements hook_views_post_execute()
 */
function at_helper_views_post_execute(&$view) {
  if ($view->name == 'event_days') {
    // Hide header map if there is no points for the day (Event Blog page)
    foreach ($view->result as $k => $v) {
      if (empty($v->field_field_pg_race_points)) {
        $view->result[$k]->field_field_core_id = array();
        $view->result[$k]->field_field_core_id_1 = array();
      }
    }
  }

}


/**
 * Implements hook_preprocess_HOOK()
 *
 * Set Event Days Blog images' caption as colorbox popup title
 */
function at_helper_preprocess_colorbox_image_formatter(&$variables) {
  if (isset($variables['field']['field_name']) && $variables['field']['field_name'] == AIRTRIBUNE_IMAGE_FIELD) {
    if (!empty($variables['item']['image_field_caption']['value'])) {
      $caption = $variables['item']['image_field_caption']['value'];
      $variables['display_settings']['colorbox_caption_custom'] = $caption;
    }
  }
}


/**
 * Implements hook_page_manager_contexts_alter()
 *
 * Add node context for event/[nid]/register page
 */
function at_helper_page_manager_contexts_alter(&$contexts, $placeholders) {
  if (arg(0) == 'event' && arg(2) == 'register') {
    $raw_node = node_load(arg(1));
    if ($raw_node->nid) {
      $node = ctools_context_create('node', $raw_node);
      panels_everywhere_site_template_add_context($contexts, $node, t('Node being viewed'), 'node', 'node');
    }
  }
}

function at_helper_init() {
  //if (arg(0) == 'events') {

  //}
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function at_helper_ctools_plugin_directory($module, $plugin) {
  if ($module == 'addressfield') {
    return 'plugins/' . $plugin;
  }
}


/**
 * Implements hook_og_membership_insert().
 *
 * Clean pilots list cache on new pilot registration
 */
function at_helper_og_membership_insert($og_membership) {

  // Check if it is user membership
  if ($og_membership->entity_type == 'user' && $og_membership->group_type == 'node') {
    // Get event id
    $gid = $og_membership->gid;
    $node = node_load($gid);
    if ($node->nid && $node->type == 'pg_contest') {
      _at_helper_clear_pilots_list_cache();
    }
  }


}

function at_helper_user_presave(&$edit, $account, $category) {
  if (isset($account->status) && isset($edit['status']) && $account->status == 0 && $edit['status'] == 1) {
    _at_helper_clear_pilots_list_cache();
  }
}

function _at_helper_clear_pilots_list_cache() {
  $cids = array(
    'paragliding_pilots_list' => 'cache_views_data',
    'paragliding_contest_pilots_stats:default:results' => 'cache_views_data',
    'panels_simple_cache:page-event_pilots:page_event_pilots_panel_context' => 'cache',
  );
  foreach ($cids as $cid => $bin) {
    cache_clear_all($cid, $bin, TRUE);
  }
}

/**
 * Implements hook_field_attach_presave()
 */
function at_helper_field_attach_presave($entity_type, $entity) {
  if ($entity_type == 'node' && $entity->type == AIRTRIBUNE_DAY_TYPE && !empty($entity->at_helper_day_form_flag)) {
    // Get day images data.
    $node_wrapper = entity_metadata_wrapper('node', $entity);
    $images_value = $node_wrapper->{AIRTRIBUNE_IMAGE_FIELD}->value();
    if (!empty($images_value)) {
      // Get referenced event data
      $og_audience_value = $node_wrapper->{OG_AUDIENCE_FIELD}->value();
      $event_title = !empty($og_audience_value[0]->title) ? $og_audience_value[0]->title : '';

      $day_number = $node_wrapper->{AIRTRIBUNE_DAY_NUMBER}->value();
      $day_number = !empty($day_number) ? 'Day' . $day_number : '';
      foreach ($images_value as $k => $v) {
        if (!empty($v['image_field_caption']['value'])) {
          $components = array($v['image_field_caption']['value'], 'Paragliding', $event_title, $day_number);
        }
        else {
          $components = array('Paragliding', $event_title, $day_number, $photo_number, sprintf('%03d', $k + 1));
        }
        $images_value[$k]['alt'] = $images_value[$k]['title'] = implode(' ', $components);
      }
      // Set updated value
      $node_wrapper->{AIRTRIBUNE_IMAGE_FIELD}->set($images_value);
    }
  }
}

/**
 * Implements hook_field_attach_form()
 */
function at_helper_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  // Set flag for image title tags change (in at_helper_field_attach_presave)
  if ($entity_type == 'node' && $entity->type == AIRTRIBUNE_DAY_TYPE) {
    $form['#node']->at_helper_day_form_flag = TRUE;
  }
}
