<?php

// TODO: Move common generic plugins alter into def submodule (def_extra).

function cde_menu() {
  $items['cde/test/%'] = array(
   'title' => 'CDE Test', 
    'page callback' => 'cde_test',
    'page arguments' => array(2),
    'access callback' => TRUE, 
    //'file' => 'abc.tmp.inc',
  );
  
  $items['event/%node/register'] = array(
   'title' => 'CDE Test', 
    'page callback' => 'cde_test2',
    'page arguments' => array(1),
    'access callback' => 'cde_access',
    'access arguments' => array(1),
    'title' => 'Registration',
    //'file' => 'abc.tmp.inc',
  );
  return $items;
}

function cde_test2($node) {
  $nid = $node->nid;
  return cde_test($nid, FALSE);
}

function cde_test($nid, $default_nid = TRUE) {
  global $user;
  
  // TODO: Temporary event id
  if ($default_nid) {
    $nid = 5438;
  }
  
  $form = $user->uid ? cde_form_authorized($nid) : cde_form_anonymous($nid);
  //dsm($form);
  return $form;
}


// TODO: Check conditions.
/**
 * Access callback for event registration page.
 */
function cde_access($node) {
  $etid = $node->nid;
  global $user;
  
  $entity_type = 'node';
  
  if (airtribune_how_time_after_event_start($etid) >= 2) {
    return FALSE;
  }

  $entity = entity_load_single($entity_type, $etid);
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);

  if (!og_user_access($entity_type, $id, 'subscribe', $user) && !og_user_access($entity_type, $id, 'subscribe without approval', $user)) {
    return FALSE;
  }

  if ($user->uid) {

    if (og_is_member($entity_type, $id, 'user', $user, array(OG_STATE_ACTIVE))
      || og_is_member($entity_type, $id, 'user', $user, array(OG_STATE_PENDING))
      || og_is_member($entity_type, $id, 'user', $user, array(OG_STATE_BLOCKED))
    ) {

      return FALSE;
    }
  }


  return TRUE;
}

function cde_form_anonymous($nid) {
  module_load_include('inc', 'og_ui', 'og_ui.pages');
  module_load_include('inc', 'cde');
  
  module_load_include('module', 'profile2');
  
  global $user;
  
  // profile2_form()
  module_load_include('inc', 'profile2', 'contrib/profile2_page');
  
  // TODO: Maybe move into abc_get_form().
  // Why do we need this flag?
  // Inform hook_js_alter() that multiform is processed.
  //~ drupal_add_js(array('cde' => array('multiform_id' => 'multiform')), 'setting');
  
  // TODO: Included file should be overriden in case of custom callback.
  // See def comment in def_ajax_defaults().
  drupal_add_js(drupal_get_path('module', 'cde') .'/js/cde.js', 'file');
  
  $profile2_init_data = cde_profile_form_init_data();
  //dsm($profile2_init_data);
  
  // TODO: Maybe use #array_parents instead of #parents in order not to confuse.
  $settings = array(
    '#multiform_id' => 'contest_registration_anonymous',
    '#subforms' => array(
      array(
        'form_id' => 'user_register_form',
        '#before_execute' => array('cde_user_register_before_execute'),
        '#after_execute' => array('cde_user_register_after_execute'),
        '#map' => array(
          // TODO:
          array(
            '#parents' => array('actions', 'submit'),
            '#triggering_submit' => array('register'),
          ),
        ),
      ),
      array(
        'form_id' => 'og_ui_confirm_subscribe',
        'args' => cde_og_form_args($nid),
        '#map' => array(
          // TODO:
          array(
            '#parents' => array('actions', 'submit'),
            '#triggering_submit' => array('register'),
          ),
        ),
      ),
      
      array(
        //'form_id' => 'entity_ui_get_form',
        'form_id' => $profile2_init_data['form_id'],
        //'args' => cde_profile_form_args(),
        'args' => $profile2_init_data['args'],
        '#preprocess_form_state' => array('cde_profile2_form_preprocess_form_state'),
        '#map' => array(
          // TODO:
          array(
            '#parents' => array('actions', 'submit'),
            '#triggering_submit' => array('register'),
          ),
        ),
      ),
      
    ),
    '#submit_map' => array(
      '#submits' => array(
        'register' => array(
          '#type' => 'submit',
          '#value' => t('Multiform register'),
        ),
      ),
    ),
    
    '#redirect_path' => 'event/' . $nid,
  );
  
  //$args = cde_profile_form_args();
  //dsm($args);
  //dsm(entity_ui_get_form($args[0], $args[1]));
  return abc_get_form($settings);
}

/**
 * Add list of generic elements to validate.
 */
function cde_form_alter(&$form, &$form_state, $form_id) {
  $def_generic_elements = array();
  
  // TODO: Add only for forms with enabled validation.
  switch ($form_id) {
    case 'user_register_form' :
      $def_generic_elements[] = array('account', 'mail');
      break;
  }
  
  def_add_generic_elements($form_state, $def_generic_elements);
}


/**
 * Implements hook_def_form_after_build().
 */
function cde_def_form_after_build($form, &$form_state) {
  if (!empty($form_state['build_info']['form_id'])) {
    if ($form_state['build_info']['form_id'] == 'user_register_form') {
      $form['account']['mail']['#element_validate'][] = 'cde_mail_validate';
    }
  }
  return $form;
}

function cde_mail_validate($element, &$form_state) {
  //$mail = trim($form_state['values']['mail']);
  //form_set_value($form['account']['mail'], $mail, $form_state);
  if ($error = user_validate_mail($form_state['values']['mail'])) {
    form_set_error('mail', $error);
  }
  elseif ((bool) db_select('users')->fields('users', array('uid'))->condition('uid', 0, '<>')
    ->condition('mail', db_like($form_state['values']['mail']), 'LIKE')->range(0, 1)->execute()->fetchField()
  ) {
    form_set_error('mail', t('This email is already registered. <br />' . l('Forgot your password?', 'user/password')));
  }
}


// TODO: Remove if not needed.
function cde_field_widget_form_alter(&$element, &$form_state, $context) {
  cde_alter_widgets($element, $form_state, $context);
}


// TODO: Check other conditions and load plugin
/**
 * Implements hook_def_field_plugin_alter().
 */
function cde_def_field_plugin_alter(&$plugin, $element, $form_state, $context) {
  
  if ($plugin['module'] == 'def' && $plugin['plugin type'] == 'field') {
    switch ($plugin['name']) {
      case 'name__name_widget' :
        $plugin_override = ctools_get_plugins('cde', 'field', 'name__name_widget');
        break;
      case 'datetime__date_select' :
        $plugin_override = ctools_get_plugins('cde', 'field', 'datetime__date_select');
        break;
      case 'number_integer__number' :
        // Check field name.
        if (!empty($context['field']['field_name']) && $context['field']['field_name'] == AIRTRIBUNE_CONTESTANT_NUMBER_FIELD) {
          $plugin_override = ctools_get_plugins('cde', 'field', 'number_integer__number');
        }
        break;
    }
    
    if (!empty($plugin_override)) {
      $plugin = $plugin_override;
    }
  }  
}

function cde_name_dateofbirth_element_validate($element, &$form_state) {
  // Here we need to validate both Name and DateOfBirth fields.
  // See field_default_extract_form_values().
  
  global $user;

  // Do nothing for authorized user.
  if ($user->uid) {
    return;
  }
  
  // TODO: Maybe extract data a different way.
  // $entity, $entity_type, $field_parents and $langcode are the same for both, Name and DateOfBirth.
  $entity = $element['#entity'];
  $entity_type = $element['#entity_type'];
  $field_parents = $element['#field_parents'];
  $langcode = LANGUAGE_NONE;
  
  
  $path[AIRTRIBUNE_USER_FULLNAME_FIELD] = array_merge($field_parents, array(AIRTRIBUNE_USER_FULLNAME_FIELD, $langcode));
  $path[AIRTRIBUNE_BIRTHDATE_FIELD] = array_merge($field_parents, array(AIRTRIBUNE_BIRTHDATE_FIELD, $langcode));
  
  $key_exists = NULL;
  $values[AIRTRIBUNE_USER_FULLNAME_FIELD] = drupal_array_get_nested_value($form_state['values'], $path[AIRTRIBUNE_USER_FULLNAME_FIELD], $key_exists);
  $key_exists = NULL;
  $values[AIRTRIBUNE_BIRTHDATE_FIELD] = drupal_array_get_nested_value($form_state['values'], $path[AIRTRIBUNE_BIRTHDATE_FIELD], $key_exists);
  
  //~ dsm($values);
  
  $given = !empty($values[AIRTRIBUNE_USER_FULLNAME_FIELD][0]['given']) ? $values[AIRTRIBUNE_USER_FULLNAME_FIELD][0]['given'] : FALSE;
  $family = !empty($values[AIRTRIBUNE_USER_FULLNAME_FIELD][0]['family']) ? $values[AIRTRIBUNE_USER_FULLNAME_FIELD][0]['family'] : FALSE;
  $birthdate = !empty($values[AIRTRIBUNE_BIRTHDATE_FIELD][0]['value']) ? $values[AIRTRIBUNE_BIRTHDATE_FIELD][0]['value'] : FALSE;
  
  if (!empty($given) && !empty($family) && !empty($birthdate)) {
    $time = new DateObject($birthdate);
    $birthdate = $time->format('Y-m-d H:i:s');
    if (!$time->validGranularity('year', 'month', 'day')) {
      return;
    }
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'profile2');
    $query->entityCondition('bundle', MAIN_PROFILE_TYPE);
    $query->fieldCondition('field_full_name', 'given', $given);
    $query->fieldCondition('field_full_name', 'family', $family);
    $query->fieldCondition('field_birthdate', 'value', $birthdate);
    $orig_query = clone $query;
    $name_exists = $query->count()->execute();
    
    if ($name_exists) {
      // TODO: choose correct element for each field.
      //~ $element = isset($form[$profile_type]) ? $form[$profile_type]['field_full_name'] : $form;
      form_error($element, t('This name, surname and date of birth combination already exist. <a href="!path">Forgot your password?</a>', array('!path' => url('user/password'))));
    }
  }
}

// TODO:
/**
 * Field Validation.
 * 
 * Check that pilot's number is unique.
 */
function cde_pilot_number_element_validate($element, &$form_state) {
  // See field_default_extract_form_values().
  
  // Group ID.
  $gid = !empty($form_state['values']['gid']) ? $form_state['values']['gid'] : FALSE;
  
  $entity = $element['value']['#entity'];
  $bundle = $element['value']['#bundle'];
  $entity_type = $element['value']['#entity_type'];
  $field_parents = $element['value']['#field_parents'];
  $langcode = $element['value']['#language'];
  
  $path = array_merge($field_parents, array(AIRTRIBUNE_CONTESTANT_NUMBER_FIELD, $langcode));
  
  $key_exists = NULL;
  $values = drupal_array_get_nested_value($form_state['values'], $path, $key_exists);
  
  if (!empty($gid) && !empty($values[0]['value']) && is_numeric($pilot_number = $values[0]['value'])) {
    
    // TODO:
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', $entity_type);
    $query->entityCondition('bundle', $bundle);
    $query->propertyCondition('gid', $gid);
    $query->fieldCondition(AIRTRIBUNE_CONTESTANT_NUMBER_FIELD, 'value', $pilot_number);
    //$query->fieldCondition('field_full_name', 'family', $family);
    $number_exists = $query->count()->execute();
    if ($number_exists) {
      // TODO:
      //~ $element = isset($form['field_contestant_number']) ? $form['field_contestant_number'] : $form;
      form_error($element, t('This number is used by another pilot.'));
    }
  }
}

function cde_form_authorized($nid) {
  module_load_include('inc', 'og_ui', 'og_ui.pages');
  module_load_include('inc', 'profile2', 'contrib/profile2_page');
  
  // TODO: Included file should be overriden in case of custom callback.
  // See def comment in def_ajax_defaults().
  drupal_add_js(drupal_get_path('module', 'cde') .'/js/cde.js', 'file');
  
  $profile2_init_data = cde_profile_form_init_data_authorized();
  
  $settings = array(
    '#multiform_id' => 'contest_registration_authorized',
    '#subforms' => array(
      array(
        'form_id' => 'og_ui_confirm_subscribe',
        'args' => cde_og_form_args($nid),
        '#map' => array(
          // TODO:
          array(
            '#parents' => array('actions', 'submit'),
            '#triggering_submit' => array('register'),
          ),
        ),
      ),
      array(
        //'form_id' => 'entity_ui_get_form',
        'form_id' => $profile2_init_data['form_id'],
        //'args' => cde_profile_form_args(),
        'args' => $profile2_init_data['args'],
        '#preprocess_form_state' => array('cde_profile2_form_preprocess_form_state'),
        '#map' => array(
          // TODO:
          array(
            '#parents' => array('actions', 'submit'),
            '#triggering_submit' => array('register'),
          ),
        ),
      ),
    ),
    '#submit_map' => array(
      '#submits' => array(
        'register' => array(
          '#type' => 'submit',
          '#value' => t('Multiform register'),
        ),
      ),
    ),
    
    '#redirect_path' => 'event/' . $nid,
  );
  
  return abc_get_form($settings);
}


// TODO: Move 'args' function into a single init_data function

function cde_og_form_args($nid) {
  global $user;
  
  $entity_type = 'node';
  $etid = $nid;
  
  $entity = entity_load_single($entity_type, $etid);
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
  $field_name = og_get_best_group_audience_field('user', $user->uid, $entity_type, $bundle);
  
  //$entity_type, $id, $user, $field_name
  return array($entity_type, $id, $user, $field_name);
}

// Based on entity_ui_get_form() version 7.x-1.2
function cde_profile_form_init_data() {
  // TODO: Include entity.module ?
  // TODO: Also see profile2_by_uid_load($uid, $type_name) in profile2_pages.module
  // TODO: Remove hardcode
  
  $entity_type = 'profile2';
  $type_name = 'pilot';
  $entity = profile2_create(array('type' => $type_name));
  
  // Based on entity_ui_get_form()
  $form_state = array();
  list(, , $bundle) = entity_extract_ids($entity_type, $entity);
  $form_id = (!isset($bundle) || $bundle == $entity_type) ? $entity_type . '_form' : $entity_type . '_edit_' . $bundle . '_form';
  
  $op = 'add';
  // TODO: Delete this line
  $form_state['build_info']['args'] = array($entity, $op, $entity_type);
  
  $data = array(
    'args' => array($entity, $op, $entity_type),
    'form_id' => $form_id,
  );
  
  return $data;
}

// TODO: see entity_ui_form_defaults() to add 'profile2' into $form_state
// via entity_ui_main_form_defaults (cde_profile2_form_preprocess_form_state())
function cde_profile_form_init_data_authorized() {
  // profile2_form()
  module_load_include('inc', 'profile2', 'contrib/profile2_page');
  
  global $user;
  $uid = $user->uid;
  
  $entity_type = 'profile2';
  $type_name = 'pilot';
  $entity = profile2_by_uid_load($uid, $type_name);
  
  // Based on entity_ui_get_form()
  $form_state = array();
  list(, , $bundle) = entity_extract_ids($entity_type, $entity);
  $form_id = (!isset($bundle) || $bundle == $entity_type) ? $entity_type . '_form' : $entity_type . '_edit_' . $bundle . '_form';
  
  // Default option. See entity_ui_get_form().
  $op = 'edit';
  
  $form_state['build_info']['args'] = array($entity, $op, $entity_type);
  
  $data = array(
    'args' => array($entity, $op, $entity_type),
    'form_id' => $form_id,
  );
  return $data;
}

// Based on entity_ui_get_form() version 7.x-1.2
function cde_profile2_form_preprocess_form_state(&$form_state) {
  $entity_type = 'profile2';
  $form_state['wrapper_callback'] = 'entity_ui_main_form_defaults';
  $form_state['entity_type'] = $entity_type;
  form_load_include($form_state, 'inc', 'entity', 'includes/entity.ui');
}



// TODO:
/**
 * Implements hook_def_validation_enabled().
 */
function cde_def_validation_enabled($element, $form_state) {
  $callback = NULL;
  
  //~ if (isset($form_state['build_info']['form_id']) && $form_state['build_info']['form_id'] == 'user_register_form') {
    $callback = 'cde_def_validation_enabled_callback';
  //~ }
  
  return $callback;
}

// TODO:
function cde_def_validation_enabled_callback($element, $form_state) {
  return TRUE;
}

// TODO:
/**
 * Implements hook_def_ajax_defaults_alter().
 */
function cde_def_ajax_defaults_alter(&$defaults, $form_state) {
  $defaults['def_commands_callback'] = 'cde_ajax_commands';
}

function cde_ajax_commands($selector, $html) {
  //~ if (empty($html)) {
    //~ $html = 'no errors';
  //~ }
  
  //~ $html = "$html $selector";
  
  return array(
    //$commands[] = ajax_command_invoke($selector, 'checkValidationResult', array($html));
    //~ ajax_command_alert($html),
    ajax_command_invoke($selector, 'checkValidationResult', array($html)),
  );
}

// =======================================================
// Ctools
// =======================================================

/**
 * Implements hook_ctools_plugin_type().
 */
// TODO: 'use hooks' ?
function cde_ctools_plugin_type() {
  // Used for field widgets.
  $plugins['field'] = array(
    'use hooks' => FALSE,
  );
  //~ // Used for generic form elements.
  //~ $plugins['generic'] = array(
    //~ 'use hooks' => FALSE,
  //~ );
  return $plugins;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function cde_ctools_plugin_directory($module, $plugin) {
  if ($module == 'cde' && $plugin == 'field') {
    return 'plugins/validators/field';
  }
  //~ if ($module == 'cde' && $plugin == 'generic') {
    //~ return 'plugins/validators/generic';
  //~ }
}


// =======================================================
// Clientside validation
// =======================================================

// TODO: This hook should be called before clientside_validation original hook.
// TODO: Check that form is multiform.
// TODO: Seems that hook is not invoked for ajax-validation.

/**
 * Implements hook_js_alter().
 */
function cde_js_alter(&$javascript) {
  
  $clientsideValidationSettingsKey = NULL;
  
  // TODO: Check for specific ids
  $multiform_ids = abc_multiform_ids();
  $is_multiform = !empty($multiform_ids) ? TRUE : FALSE;
  
  // Check for clientside_validation settings.
  foreach ($javascript['settings']['data'] as $k => $setting) {
      if (!empty($setting['clientsideValidation']['forms'])) {
        $clientsideValidationSettingsKey = $k;
        break;
      }
  }
  
  // Do nothing if there is no clientside_validation settings.
  if (!isset($clientsideValidationSettingsKey)) {
    return;
  }
  
  
  $k = $clientsideValidationSettingsKey;
  $setting = $javascript['settings']['data'][$k];
  //~ dsm($setting);
  
  // Set custom function for error placement.
  foreach ($setting['clientsideValidation']['forms'] as $form_key => $form_settings) {
    $setting['clientsideValidation']['forms'][$form_key]['errorPlacement'] = 7;
    $setting['clientsideValidation']['forms'][$form_key]['customErrorFunction'] = 'setErrorElement';
  }
  
  // If there is no multiform
  if (!$is_multiform) {
    
    if (isset($setting['clientsideValidation']['forms']['user-register-form'])) {
      $rules =& $setting['clientsideValidation']['forms']['user-register-form']['rules'];
      _cde_rules($rules);
    }
  }
  
  // Preprocess settings for multiform.
  // TODO: This is temporary solution.
  // There could also be regular forms on multiform page.
  else {

    
    // TODO:
    // For now we just copy settings of first subform.
    $multiform_setting = reset($setting['clientsideValidation']['forms']);
    
    $rules = array();
    
    foreach ($setting['clientsideValidation']['forms'] as $f => $subform_setting) {
      
      _cde_rules($subform_setting['rules'], TRUE);
      
      $rules += $subform_setting['rules'];
    }
    $multiform_setting['rules'] = $rules;
    
    $setting['clientsideValidation']['forms'] = array('multiform' => $multiform_setting);
  }
  
  $javascript['settings']['data'][$k] = $setting;
}


/**
 * Implements hook_ajax_render_alter().
 * 
 * Change Drupal.settings for the case when ajax-callback returns $commands,
 * since hook_js_alter isn't called.
 * 
 * Here we need to add 'multiform' for every clientside_validation setting key.
 * Alse there is a bug with clientside_validation when form_state['rebuild'] == TRUE. See #3928
 */
function cde_ajax_render_alter(&$commands) {
  //
  
  foreach ($commands as $k => $command) {
    if (isset($command['settings']['clientsideValidation']['forms'])) {
      $forms =& $command['settings']['clientsideValidation']['forms'];
      
      // TODO: Check for specific ids
      $multiform_ids = abc_multiform_ids();
      $is_multiform = !empty($multiform_ids) ? TRUE : FALSE;
      
      if (isset($forms['user-register-form'])) {
        if ($is_multiform) {
          $forms['multiform'] = $forms['user-register-form'];
          unset($forms['user-register-form']);
        }
      }
      
      if (isset($forms['profile2-edit-pilot-form'])) {
        // TODO:
        if ($is_multiform) {
          $forms['multiform'] = $forms['profile2-edit-pilot-form'];
          unset($forms['profile2-edit-pilot-form']);
        }
        unset($forms['profile2-edit-pilot-form--2']);
      }
      
      if (isset($forms['og-ui-confirm-subscribe'])) {
        // TODO:
        if ($is_multiform) {
          $forms['multiform'] = $forms['og-ui-confirm-subscribe'];
          unset($forms['og-ui-confirm-subscribe']);
        }
        // Exclude?
        unset($forms['og-ui-confirm-subscribe--2']);
      }
      
      // Exclude?
      if (isset($forms['profile2-edit-main-form'])) {
        // TODO:
        if ($is_multiform) {
          $forms['multiform'] = $forms['profile2-edit-main-form'];
          unset($forms['profile2-edit-main-form']);
        }
        unset($forms['profile2-edit-main-form--2']);
      }
      
      $commands[$k] = $command;
      //~ dsm($command);
      break;
    }

  }
}




/**
 * Override clientside_validation js rules.
 */
function _cde_rules(&$rules, $multiform = FALSE) {
  
  $english_only_message = t('This field may contain only English letters.');
  
  static $multiform_rules = NULL;
  
  // TODO: Remove 'form_id' key
  // TODO: profile_main has a differrent multiform form_id for authenticated users.
  $new_rules = array(
    'profile_main[field_full_name][und][0][given]' => array(
      'required' => TRUE,
      'messages' => array(
        'required' => t('Name is required.'),
        'regexMatch' => $english_only_message,
      ),
      'form_id' => 'user_register_form',
    ),
    'profile_main[field_full_name][und][0][family]' => array(
      'required' => TRUE,
      'messages' => array(
        'required' => t('Surname is required.'),
        'regexMatch' => $english_only_message,
      ),
      'form_id' => 'user_register_form',
    ),
    
    'pass[pass1]' => array(
      'passwordStrength' => TRUE,
      'messages' => array(
        'required' => t('Password is required.'),
        'passwordStrength' => t('This password is too easy to guess.'),
      ),
      'form_id' => 'user_register_form',
    ),
    
    'pass[pass2]' => array(
      'passwordConfirmation' => TRUE,
      'messages' => array(
        'required' => t('Type the password in both fields.'),
        'passwordConfirmation' => t('Passwords do not match.'),
      ),
      'form_id' => 'user_register_form',
    ),
    
    'profile_main[field_birthdate][und][0][value][month]' => array(
      'required' => TRUE,
      'form_id' => 'user_register_form',
    ),
    'profile_main[field_birthdate][und][0][value][year]' => array(
      'required' => TRUE,
      'form_id' => 'user_register_form',
    ),
    'profile_main[field_birthdate][und][0][value][day]' => array(
      'required' => TRUE,
      'form_id' => 'user_register_form',
    ),
    
    // ADDRESS
    // TODO: Check if regexMatch is added correctly (relates to array_merge_recursive_distinct()).
    'profile_pilot[field_address][und][0][thoroughfare]' => array(
      'regexMatch' => array(
        0 => '^[\x20-\x7F]+$',
      ),
      'messages' => array(
        'regexMatch' => $english_only_message,
      ),
      'form_id' => 'profile2_edit_pilot_form',
    ),
    
    'profile_pilot[field_address][und][0][premise]' => array(
      'regexMatch' => array(
        0 => '^[\x20-\x7F]+$',
      ),
      'messages' => array(
        'regexMatch' => $english_only_message,
      ),
      'form_id' => 'profile2_edit_pilot_form',
    ),
    
    'profile_pilot[field_address][und][0][locality]' => array(
      'regexMatch' => array(
        0 => '^[\x20-\x7F]+$',
      ),
      //~ 'messages' => array(
        //~ 'regexMatch' => $english_only_message,
      //~ ),
      'form_id' => 'profile2_edit_pilot_form',
    ),
    
    // CIVL ID
    'profile_pilot[field_civl_id][und][0][value]' => array(
      'messages' => array(
        'digits_negative' => t('CIVL ID may contain only digits.'),
      ),
      'form_id' => 'profile2_edit_pilot_form',
    ),
  );
  
  // TODO:
  $unset_rules = array(
    'profile_pilot[field_address][und][0][postal_code]' => array(
      'regexMatch',
    ),
    'profile_pilot[field_address][und][0][country]' => array(
      'regexMatch',
    ),
    
    //Phone number select
    'profile_pilot[field_phone][und][0][country_codes]',
    'profile_pilot[field_person_phone][und][0][country_codes]',
  );
  
  
  
  if (!$multiform) {
    cde_tmp_clean_new_rules($new_rules);
    
    // First find array_intersect to add rules for existing components only.
    $new_rules = array_intersect_key($new_rules, $rules);
    // Add or override rules.
    $rules = array_merge_recursive_distinct($rules, $new_rules);
  }
  else {
    if (empty($multiform_rules)) {
      cde_tmp_new_rules_multiform_keys($new_rules);
      cde_tmp_clean_new_rules($new_rules);
      $multiform_rules = $new_rules;
    }
    else {
      $new_rules = $multiform_rules;
    }
    //~ dsm($new_rules);
    //~ $new_rules = array_intersect_key($new_rules, $rules);
    $rules = array_merge_recursive_distinct($rules, $new_rules);
  }
  //~ dsm($rules);
}

// TODO: Remove
// This is a temporary function
function cde_tmp_clean_new_rules(&$new_rules) {
  foreach ($new_rules as $k => $new_rule) {
    if (isset($new_rules[$k]['form_id'])) {
      unset($new_rules[$k]['form_id']);
    }
  }
}

// TODO: Remove
// This is a temporary function
function cde_tmp_new_rules_multiform_keys(&$new_rules) {
  foreach ($new_rules as $k => $new_rule) {
    if (isset($new_rule['form_id'])) {
      if (strpos($k, 'multiform') === 0) {
        continue;
      }
      $form_id = $new_rule['form_id'];
      $new_key = "multiform[$form_id]" . preg_replace('/^[^[]+/', '[\0]', $k);
      $new_rules[$new_key] = $new_rules[$k];
    }
    
    unset($new_rules[$k]);
  }
}


// http://www.php.net/manual/ru/function.array-merge-recursive.php#92195
function array_merge_recursive_distinct (&$array1, &$array2) {
  $merged = $array1;
  foreach ($array2 as $key => &$value) {
    if (is_array ($value) && isset($merged[$key]) && is_array($merged[$key])) {
      $merged[$key] = array_merge_recursive_distinct($merged[$key], $value);
    }
    else {
      $merged[$key] = $value;
    }
  }
  return $merged;
}











// =======================================================
// Misc
// =======================================================


/**
 * Implements hook_field_widget_form_alter().
 *
 * Adds ajax handler to field widgets.
 * Ctools plugins should be used for individual handlers.
 */
function cde_alter_widgets(&$element, &$form_state, $context) {
  // TODO: Move to a single function.
  // Change field_t_shirt_size default select option name.
  if ($element['#field_name'] == 'field_t_shirt_size') {
    $element['#after_build'][] = '_t_shirt_size_after_build';
  }
  // Change field_blood_type default select option name.
  if ($element['#field_name'] == 'field_blood_type') {
    $element['#after_build'][] = '_blood_type_after_build';
  }
  // Change field_address default select option name.
  if ($element['#field_name'] == 'field_address') {
    $element['#after_build'][] = '_address_after_build';
  }
  // Change field_birthdate components order.
  if ($element['#field_name'] == 'field_birthdate') {
    $element['#after_build'][] = '_birthdate_after_build';
  }
  // Change field_full_name components description.
  if ($element['#field_name'] == 'field_full_name') {
    $element['#after_build'][] = '_full_name_after_build';
  }
}


/**
 * After build for field_t_shirt_size field widget.
 */
function _t_shirt_size_after_build($element, $form_state) {
  $options = array('_none' => t('Select your size'));
  $options += $element['#options'];
  $element['#options'] = $options;
  return $element;
}

/**
 * After build for field_blood_type field widget.
 */
function _blood_type_after_build($element, $form_state) {
  $options = array('_none' => t('Select your type'));
  $options += $element['#options'];
  $element['#options'] = $options;
  return $element;
}

/**
 * After build for field_address field widget.
 */
function _address_after_build($element, $form_state) {
  // Add extra blank option.
  $options = array('' => t('Select your country'));
  foreach ($element['country']['#options'] as $k => $v) {
    $options[$k] = $v;
  }
  $element['country']['#options'] = $options;

  // Change components' order.
  $element['locality_block']['#weight'] = 0;
  $element['street_block']['#weight'] = 1;
  $element['locality_block']['postal_code']['#weight'] = 0;
  $element['locality_block']['locality']['#weight'] = 0.001;
  $element['locality_block']['#sorted'] = FALSE;

  return $element;
}

/**
 * After build for field_birthdate field widget.
 */
function _birthdate_after_build($element, $form_state) {
  //dsm($element);
  $element['value']['month']['#weight'] = 1;
  $element['value']['day']['#weight'] = 0;
  return $element;
}

/**
 * After build for field_birthdate field widget.
 */
function _full_name_after_build($element, $form_state) {
  $element['given']['#description'] = t('Your name in English transcription.');
  $element['family']['#description'] = t('Your surname in English transcription.');
  return $element;
}




// =======================================================
// Crossfields
// =======================================================


// TODO:

/**
 * Implements hook_multiform_crossfields().
 */
function cde_multiform_crossfields($multiform) {
  $items = array();

  // TODO: Also add contest_registration_authorized
  if (in_array($multiform['#multiform_id'], array('contest_registration_anonymous', 'contest_registration_authorized'))) {
    $field_names = array(
      'field_paraglider_manufacturer',
      'field_paraglider_model',
      'field_paraglider_color',
      'field_phone'
    );
    foreach ($field_names as $field_name) {
      $items[] = array(
        '#dependent' => array(
          '#tag' => 'og_ui_confirm_subscribe',
          '#name' => $field_name,
          '#parents' => array($field_name),
          '#array_parents' => array($field_name),
        ),
        '#base' => array(
          '#tag' => 'profile2_edit_pilot_form',
          '#name' => $field_name,
          '#parents' => array('profile_pilot', $field_name),
          '#array_parents' => array('profile_pilot', $field_name),
        ),
      );
    }
  }

  return $items;
}

