<?php
/**
 * @file
 * Code for the Accommodation feature.
 */

include_once 'accommodation.features.inc';


/**
 * Implements hook_node_info().
 */
function accommodation_node_info() {
  $items = array(
    'accommodation' => array(
      'name' => t('Accommodation'),
      'base' => 'accommodation',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}